package com.ratka.dartscore

import android.Manifest
import android.app.Activity
import android.content.Context
import android.content.pm.PackageManager
import android.net.ConnectivityManager
import android.net.Network
import android.net.NetworkCapabilities
import android.net.NetworkRequest
import android.net.wifi.WifiManager
import android.net.wifi.WifiNetworkSpecifier
import android.os.Build
import android.os.Handler
import android.os.Looper
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MethodCall
import io.flutter.plugin.common.MethodChannel

/**
 * Raises a Wi-Fi network of this device's own for one transfer, and joins one
 * another device raised.
 *
 * The point is the transfer that has no shared Wi-Fi to run over, or one whose
 * router refuses to let two devices talk to each other. A local only hotspot is
 * a network with nothing on it but the two phones, so neither can happen.
 *
 * Written by hand rather than taken from a package, like the document picker
 * beside it: the maintained options either want CocoaPods on the iOS side or
 * ship Kotlin sources this project's Gradle setup cannot take.
 *
 * Both halves are gated at Android 13. Below that the same work needs
 * ACCESS_FINE_LOCATION and the user's location switched on, which is a heavy
 * thing to ask of a darts app and a declaration to file with the store. From 13
 * `NEARBY_WIFI_DEVICES` covers it with `neverForLocation`, so nothing about
 * where the user is comes into it. Older devices fall back on the transfer over
 * a shared Wi-Fi.
 */
class LocalHotspotHandler(private val activity: Activity) {
    /** Shared with `LocalHotspot` on the Dart side. */
    private val hotspotChannelName = "dartscore/local_hotspot"

    /** Shared with `WifiJoin` on the Dart side. */
    private val joinChannelName = "dartscore/wifi_join"

    private val requestNearbyDevices = 0x0BAD

    private var hotspotChannel: MethodChannel? = null

    /** The running hotspot, or null when none was raised. */
    private var reservation: WifiManager.LocalOnlyHotspotReservation? = null

    /** The start waiting for the permission dialog to come back, or null. */
    private var awaitingPermission: MethodChannel.Result? = null

    /** The join in place, so it can be given back on leave. */
    private var joinCallback: ConnectivityManager.NetworkCallback? = null

    private val wifiManager
        get() = activity.applicationContext.getSystemService(Context.WIFI_SERVICE) as WifiManager

    private val connectivityManager
        get() = activity.applicationContext
            .getSystemService(Context.CONNECTIVITY_SERVICE) as ConnectivityManager

    /** Both channels this handler answers. */
    fun attach(messenger: BinaryMessenger) {
        hotspotChannel = MethodChannel(messenger, hotspotChannelName).apply {
            setMethodCallHandler { call, result -> onHotspotCall(call, result) }
        }
        MethodChannel(messenger, joinChannelName).setMethodCallHandler { call, result ->
            onJoinCall(call, result)
        }
    }

    private fun onHotspotCall(call: MethodCall, result: MethodChannel.Result) {
        when (call.method) {
            "isSupported" -> result.success(isSupported())
            "start" -> startHotspot(result)
            "stop" -> {
                stopHotspot()
                result.success(null)
            }
            else -> result.notImplemented()
        }
    }

    private fun onJoinCall(call: MethodCall, result: MethodChannel.Result) {
        when (call.method) {
            "isSupported" -> result.success(isSupported())
            "join" -> join(
                call.argument<String>("ssid").orEmpty(),
                call.argument<String>("passphrase").orEmpty(),
                result,
            )
            "leave" -> {
                leave()
                result.success(null)
            }
            else -> result.notImplemented()
        }
    }

    private fun isSupported() = Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU

    // ── Hosting ───────────────────────────────────────────────────────────────

    /**
     * Raises the hotspot and answers with its SSID and passphrase.
     *
     * Both are generated by the system and cannot be chosen. That costs nothing
     * here: the user never types them, they travel inside the QR code.
     */
    private fun startHotspot(result: MethodChannel.Result) {
        if (!isSupported()) {
            result.error("unsupported", "This device cannot host a transfer network", null)
            return
        }
        if (reservation != null) {
            result.error("already_running", "A transfer network is already up", null)
            return
        }
        if (awaitingPermission != null) {
            result.error("already_running", "A transfer network is already starting", null)
            return
        }

        if (!hasNearbyDevicesPermission()) {
            awaitingPermission = result
            activity.requestPermissions(
                arrayOf(Manifest.permission.NEARBY_WIFI_DEVICES),
                requestNearbyDevices,
            )
            return
        }
        raiseHotspot(result)
    }

    private fun hasNearbyDevicesPermission() =
        activity.checkSelfPermission(Manifest.permission.NEARBY_WIFI_DEVICES) ==
            PackageManager.PERMISSION_GRANTED

    private fun raiseHotspot(result: MethodChannel.Result) {
        val callback = object : WifiManager.LocalOnlyHotspotCallback() {
            override fun onStarted(started: WifiManager.LocalOnlyHotspotReservation) {
                reservation = started
                val config = started.softApConfiguration
                val ssid = config.wifiSsid?.let { String(it.bytes, Charsets.UTF_8) }
                val passphrase = config.passphrase
                if (ssid == null || passphrase == null) {
                    // A network nobody can be told how to join is no better than
                    // none, and leaving it up would only drain the battery.
                    stopHotspot()
                    result.error("no_credentials", "The network reported no credentials", null)
                    return
                }
                result.success(mapOf("ssid" to ssid, "passphrase" to passphrase))
            }

            override fun onFailed(reason: Int) {
                reservation = null
                result.error(failureCode(reason), "The transfer network could not be started", null)
            }

            override fun onStopped() {
                // The system took it down, most often because Wi-Fi was turned
                // off. The screen has to hear about it or it waits on a network
                // that is gone.
                reservation = null
                hotspotChannel?.invokeMethod("stopped", null)
            }
        }

        try {
            wifiManager.startLocalOnlyHotspot(callback, Handler(Looper.getMainLooper()))
        } catch (e: SecurityException) {
            result.error("permission_denied", e.message, null)
        } catch (e: IllegalStateException) {
            result.error("already_running", e.message, null)
        }
    }

    /**
     * Why the system refused, told apart so each can be answered on screen.
     *
     * `incompatible_mode` is the common one and the only one the user can fix
     * themselves: it means the ordinary tethering hotspot is already running.
     */
    private fun failureCode(reason: Int) = when (reason) {
        WifiManager.LocalOnlyHotspotCallback.ERROR_NO_CHANNEL -> "no_channel"
        WifiManager.LocalOnlyHotspotCallback.ERROR_INCOMPATIBLE_MODE -> "incompatible_mode"
        WifiManager.LocalOnlyHotspotCallback.ERROR_TETHERING_DISALLOWED -> "tethering_disallowed"
        else -> "failed"
    }

    /** Takes the hotspot down. Safe to call when none is up. */
    fun stopHotspot() {
        reservation?.close()
        reservation = null
    }

    // ── Joining ───────────────────────────────────────────────────────────────

    /**
     * Joins [ssid] and routes this app's own traffic over it.
     *
     * The binding is the part that is easy to leave out and impossible to work
     * around afterwards: a transfer network carries no internet, so Android
     * keeps sending everything over mobile data unless the process is bound to
     * the network explicitly. Without it the sockets go out over the cellular
     * interface and never reach the phone two feet away.
     */
    private fun join(ssid: String, passphrase: String, result: MethodChannel.Result) {
        if (!isSupported()) {
            result.error("unsupported", "This device cannot join from inside the app", null)
            return
        }
        if (joinCallback != null) leave()

        val specifier = WifiNetworkSpecifier.Builder()
            .setSsid(ssid)
            .setWpa2Passphrase(passphrase)
            .build()
        val request = NetworkRequest.Builder()
            .addTransportType(NetworkCapabilities.TRANSPORT_WIFI)
            .removeCapability(NetworkCapabilities.NET_CAPABILITY_INTERNET)
            .setNetworkSpecifier(specifier)
            .build()

        var answered = false
        val callback = object : ConnectivityManager.NetworkCallback() {
            override fun onAvailable(network: Network) {
                connectivityManager.bindProcessToNetwork(network)
                if (!answered) {
                    answered = true
                    result.success(null)
                }
            }

            override fun onUnavailable() {
                if (!answered) {
                    answered = true
                    result.error("join_failed", "The transfer network was not joined", null)
                }
            }

            override fun onLost(network: Network) {
                // Only meaningful after the join succeeded. The transfer either
                // finished, in which case the screen is leaving anyway, or it
                // broke, and holding a binding to a network that is gone would
                // leave the app with no route at all.
                connectivityManager.bindProcessToNetwork(null)
            }
        }
        joinCallback = callback

        try {
            connectivityManager.requestNetwork(request, callback)
        } catch (e: SecurityException) {
            joinCallback = null
            result.error("permission_denied", e.message, null)
        }
    }

    /**
     * Gives the network back and puts this app's traffic on the ordinary route.
     *
     * Has to run on every way out of a transfer, the failures included. An app
     * left bound to a network that is gone has no route to anything.
     */
    fun leave() {
        connectivityManager.bindProcessToNetwork(null)
        joinCallback?.let {
            try {
                connectivityManager.unregisterNetworkCallback(it)
            } catch (e: IllegalArgumentException) {
                // Already unregistered. Nothing to give back.
            }
        }
        joinCallback = null
    }

    /** Answers the start that was waiting on the permission dialog. */
    fun onRequestPermissionsResult(requestCode: Int, grantResults: IntArray) {
        if (requestCode != requestNearbyDevices) return
        val result = awaitingPermission ?: return
        awaitingPermission = null

        val granted = grantResults.isNotEmpty() &&
            grantResults[0] == PackageManager.PERMISSION_GRANTED
        if (granted) {
            raiseHotspot(result)
        } else {
            result.error("permission_denied", "Nearby devices permission was refused", null)
        }
    }
}
